### ISSUE TITLE
Feature: convert screenboards

### ISSUE THREAD

**Issue by yafsn** [amnk/dd2tf#10]
Has there been any thought to also converting screenboards?  I'd tried using [dashconverter.py](https://github.com/DataDog/Miscellany/blob/master/dashconverter.py) and then exporting that, but it reformatted everything.

**Comment by amnk** [comment]
@yafsn I had no immediate need in that initially, but that is a good idea. I'll take a look.

**Comment by yafsn** [comment]
Cool.  We'd moved away from screenboards in the interim, but if we come back around to them I'll definitely give it a go.
