### ISSUE TITLE
Conditional format is missing

### ISSUE THREAD

**Issue by Falydoor** [amnk/dd2tf#14]
Hello,

First of all, thank you for this tool! It is pretty useful for my team since we do use Terraform a lot.

I'm able to export one dashboard that contains a **toplist** graph with conditional format but the conditional format is missing in the generated file.

I built the binary using the commit e31218157af4e3d187354fd2a20834a91b393f97.

**Comment by amnk** [comment]
@Falydoor Thanks for the good words. I'm happy that it is useful!

I've submitted a fix, but I don't have access to such dashboard right now. Would it be possible for you to build and test it?

**Comment by Falydoor** [comment]
I builded the branch and the fix works!

Thank you 👍

**Comment by amnk** [comment]
@Falydoor awesome, thanks! Would you find any other issues (and I'm sure there are plenty) - feel free to submit issues :)
