### ISSUE TITLE
Generate build artefacts

### ISSUE THREAD

**Issue by lucioveloso** [amnk/dd2tf#16]
Hi,

Pretty cool the tool. Thanks for sharing. How about we add Github release/tag and also add the binaries for download?

**Comment by amnk** [comment]
@lucioveloso yeah, I wanted to do this for some time now, and was waiting for Travis to finish their [migration to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/). 

But probably it does not make any sense to wait, so I'll configure it shortly.

Thanks for the idea!

**Comment by amnk** [comment]
@lucioveloso I did initial [v0.1c](https://github.com/amnk/dd2tf/releases/tag/v0.1c) release.

**Comment by lucioveloso** [comment]
Awesome. Should we close the issue? =)
